### PR TITLE
Add documenting comments to orderly.json schema

### PR DESCRIPTION
**Pull request by david-mears-2**
To clarify the intent behind the properties/what terms refer to

### CODE REVIEW

**Comment by david-mears-2** [comment]
Unfortunately the 'windows-latest' R-CMD-check fails. I re-ran it and it failed again.

**Comment by plietar** [comment]
@richfitz how is this schema coordinated across repos (if at all)?

We have https://github.com/mrc-ide/outpack for the outpack schemas, but I can't find any equivalent for `orderly.json`.

**Comment by plietar** [comment]
I couldn't reproduce the build failure on a Windows VM :disappointed:

**Comment by richfitz** [comment]
The idea was that orderly2 is responsible for its schemas, it would hold them itself.  It imports schemas from outpack (there's a script somewhere to pull them in)

**Review by richfitz — APPROVED** [review]

**Pull request merged**
